name: Generate snake animation 🐍

# Run daily at 01:00 AM UTC
on:
  schedule:
    - cron: "0 01 * * *"
  workflow_dispatch:

jobs:
  snake:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      # Generate a contributions graph snake game for <github_user_name>
      - name: Generate snake animations
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          # Light - https://coolors.co/gradient-palette/e4e2e2-98ed3f?number=5
          # Dark - https://coolors.co/gradient-palette/161719-98ed3f?number=5
          outputs: |
            build/github-contribution-grid-snake.svg?color_snake=#fa66ed&color_dots=#E4E2E2,#D1E5B9,#BEE891,#ABEA68,#98ED3F
            build/github-contribution-grid-snake-dark.svg?color_snake=#fa66ed&color_dots=#161719,#374D23,#57822C,#78B836,#98ED3F
      # Push the contents of <build_dir> to a branch
      # Available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file>
      - name: Push snake animations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: crazy-max/ghaction-github-pages@v4.2.0
        with:
          build_dir: build
          target_branch: snake
